### ISSUE TITLE
Please add our paper

### ISSUE THREAD

**Issue by newlei** [jason718/awesome-self-supervised-learning#104]
Could you maybe add this paper, which uses self-supervised learning for Recommendation? Thanks!

Set2setRank: Collaborative Set to Set Ranking for Implicit Feedback based Recommendation
[pdf](https://arxiv.org/abs/2105.07377)
[code](https://github.com/newlei/Set2setRank)
Lei, Chen and Le, Wu and Kun, Zhang and  Richang, Hong and Meng, Wang. SIGIR 2021

**Comment by jason718** [comment]
can you submit a PR?
