### ISSUE TITLE
Add new SOTA Contrastive Learning methods

### ISSUE THREAD

**Issue by sccbhxc** [jason718/awesome-self-supervised-learning#128]
We appreciate your effort on the maintenance of this awesome repository.
We would like to recommend our recent research works on contrastive learning, which achieve state-of-the-art performance on popular benchmarks.
The papers are listed as follows:
[Inter-Instance Similarity Modeling for Contrastive Learning](https://arxiv.org/abs/2306.12243)
[Asymmetric Patch Sampling for Contrastive Learning](https://arxiv.org/abs/2306.02854)
Both of them provides open source code and trained model weights at Github, which can be found at following links:
https://github.com/visresearch/patchmix
https://github.com/visresearch/aps

Thanks!

**Comment by jason718** [comment]
merged you pr.
