### ISSUE TITLE
Missing paper

### ISSUE THREAD

**Issue by sdimi** [jason718/awesome-self-supervised-learning#133]
Cool list! May I suggest adding the following paper to the Timeseries section:

>Deldari, Shohreh, Dimitris Spathis, Mohammad Malekzadeh, Fahim Kawsar, Flora D. Salim, and Akhil Mathur. "CroSSL: Cross-modal Self-Supervised Learning for Time-series through Latent Masking." In Proceedings of the 17th ACM International Conference on Web Search and Data Mining, pp. 152-160. 2024. https://arxiv.org/abs/2307.16847

**Comment by jason718** [comment]
PR please. I'll accept.
