### ISSUE TITLE
Paper suggestion

### ISSUE THREAD

**Issue by samarth-robo** [jason718/awesome-self-supervised-learning#17]
Hi @jason718, could you maybe add this paper, which uses self-supervised learning for image-based localization? Thanks!
-  Geometry-Aware Learning of Maps for Camera Localization. 
  [[pdf]](https://arxiv.org/pdf/1712.03342.pdf) 
  [[code]](https://github.com/NVlabs/geomapnet)
  - Samarth Brahmbhatt, Jinwei Gu, Kihwan Kim, James Hays, and Jan Kautz. *CVPR 2018*

**Comment by jason718** [comment]
@samarth-robo  done.
