### ISSUE TITLE
A nice collection 

### ISSUE THREAD

**Issue by Wann-Jiun** [jason718/awesome-self-supervised-learning#20]
It's a nice repo! Just wondering why you didn't include the work from the Yann LeCun's group (did you)? I thought the name "self-supervised-learning" came from his group...maybe I was wrong since I am new to self-supervised-learning...:)

**Comment by jason718** [comment]
@Wann-Jiun I include some of his talk, but I haven't really watched his talk/read his recent papers lol. Will leave this open and address properly after NeurIPS. Thanks for suggestions~ I would be appreciated if you could contribute.
