### ISSUE TITLE
Paper addition in Other category.

### ISSUE THREAD

**Issue by aqibsaeed** [jason718/awesome-self-supervised-learning#28]
Multi-task Self-Supervised Learning for Human Activity Detection.
https://dl.acm.org/citation.cfm?id=3328932 (Official Link), https://arxiv.org/pdf/1907.11879.pdf (PDF)
Aaqib Saeed, Tanir Ozcelebi, Johan Lukkien. Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies.

**Comment by aqibsaeed** [comment]
Any reason this is not added yet?

**Comment by Aiiiiii** [comment]
> Any reason this is not added yet?
Would you mind publishing the code of this paper?
