### ISSUE TITLE
Paper addition in Audio category.

### ISSUE THREAD

**Issue by cheerTT** [jason718/awesome-self-supervised-learning#29]
The Sound of Pixels. 
https://eccv2018.org/openaccess/content_ECCV_2018/papers/Hang_Zhao_The_Sound_of_ECCV_2018_paper.pdf (Official Link), https://arxiv.org/pdf/1907.11879.pdf (PDF)
https://github.com/hangzhaomit/Sound-of-Pixels (CODE)
Zhao, Hang and Gan, Chuang and Rouditchenko, Andrew and Vondrick, Carl and McDermott, Josh and Torralba, Antonio.

**Comment by jason718** [comment]
added
