### ISSUE TITLE
great repo, missed at least two references, :)

### ISSUE THREAD

**Issue by jwyang** [jason718/awesome-self-supervised-learning#4]
Great collection. Two papers missed probably:

Joint Unsupervised Learning of Deep Representations and Image Clusters. CVPR 2016 (yes, I am one of the authors, :))

Unsupervised Deep Embedding for Clustering Analysis. ICML 2016

**Comment by jason718** [comment]
Added! 
Thanks for suggestion. Your paper is very interesting. The SOTA paper right now (Caron etal. 2018) is also doing clustering, and is actually not far from supervised methods.
