### ISSUE TITLE
Update the info of the survey paper 'Self-supervised Visual Feature Learning with Deep Neural Networks: A Survey'

### ISSUE THREAD

**Issue by LongLong-Jing** [jason718/awesome-self-supervised-learning#65]
@jason718 

This is a really helpful list for the self-supervised learning.

The survey paper 'Self-supervised Visual Feature Learning with Deep Neural Networks: A Survey.' is accepted by TPAMI 2020. Can you help to update it? Thanks!

The IEEE link is: https://ieeexplore.ieee.org/abstract/document/9086055

**Comment by jason718** [comment]
#66
