### ISSUE TITLE
code for DeepCluster and SwAV

### ISSUE THREAD

**Issue by mathildecaron31** [jason718/awesome-self-supervised-learning#71]
Hi, thanks for this great list of works, it's been very useful ! Would you be able to add links to codes for the following two papers please :) ?

- DeepCluster (Deep Clustering for Unsupervised Learning of Visual Features): https://github.com/facebookresearch/deepcluster
- SwAV (Unsupervised Learning of Visual Features by Contrasting Cluster Assignments): https://github.com/facebookresearch/swav

**Comment by jason718** [comment]
@mathildecaron31 updated. Thanks~
