### ISSUE TITLE
Review paper suggestion

### ISSUE THREAD

**Issue by sergiuoprea** [jason718/awesome-self-supervised-learning#95]
Hi @jason718 . Could you maybe add this review paper on future video frame prediction? Many thanks!

- A Review on Deep Learning Techniques for Video Prediction ([arxiv](https://arxiv.org/abs/2004.05214), [pami](https://doi.ieeecomputersociety.org/10.1109/TPAMI.2020.3045007))
- Sergiu Oprea, Pablo Martinez-Gonzalez, Alberto Garcia-Garcia, John Alejandro Castro-Vargas, Sergio Orts-Escolano, Jose Garcia-Rodriguez, and Antonis Argyros.
- T-PAMI (2020)

**Comment by jason718** [comment]
can you make a PR? thx~
