### ISSUE TITLE
Please add our paper

### ISSUE THREAD

**Issue by prinshul** [jason718/awesome-self-supervised-learning#98]
Hi,

Thanks for maintaining this repository. Appreciate your efforts.

Please add our paper "Contrastive Semi-Supervised Learning for 2D Medical Image Segmentation" that provides a novel way
to learn powerful representations in Semi-Supervised Setting using Contrastive Learning for images.
arXiv: https://arxiv.org/abs/2106.06801

The paper is accepted at MICCAI 2021.

**Comment by jason718** [comment]
Can you make a PR? I probably don't have time to read it in detail, and don't know how to best categorize it.
